### ISSUE TITLE
Remove Hardcode User PI

### ISSUE THREAD

**Issue by esfomeado** [toolboc/psx-pi-smbshare#24]
You should use the current use home directory instead of having the user PI hardcoded.

**Comment by toolboc** [comment]
We default to the pi user because is the standard employed in existing [Raspbian documentation](https://www.raspberrypi.org/documentation/linux/usage/users.md).  

As of writing, there are three places in the code that need to reference the pi user explicitly:
* https://github.com/toolboc/psx-pi-smbshare/blob/7b6122d4358dea7deaf9cd4671a475cb8acc2748/automount-usb.sh#L70
* https://github.com/toolboc/psx-pi-smbshare/blob/7b6122d4358dea7deaf9cd4671a475cb8acc2748/automount-usb.sh#L92
* https://github.com/toolboc/psx-pi-smbshare/blob/d49fda3c49218a3a364cdeaa7222337dc1808701/samba-init.sh#L31

There are also multiple references to the path `/home/pi` in setup.sh, this ensures that files are accessible to the default pi user after installing with 'sudo':
* https://github.com/toolboc/psx-pi-smbshare/blob/841b757a333f2919fe52ed1421caa224fe1d620a/setup.sh

We make these assumptions because we explicitly support Raspbian in the release images, where the pi user is expected to exist.  I suppose this would break custom installs on devices that do not have this user present, which is technically an unsupported use case.  Perhaps it could be investigated to support a mechanism that allows you to install everything for a custom user, assuming this would have broad appeal and be a benefit to a new audience.  Has this assumption caused issues for you?
